apiVersion: apps/v1
kind: Deployment
metadata:
  name: junjun-deployment
spec:
  replicas: 2  # 어플리케이션 Pod 수
  selector:
    matchLabels:
      app: junjun-app
  template:
    metadata:
      labels:
        app: junjun-app
    spec:
      containers:
      - name: junjun-container
        image: hojun5513/junjunbaristudio-web:latest
        ports:
        - containerPort: 80
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: DB_PORT
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: POSTGRES_PASSWORD
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: REDIS_HOST
          - name: REDIS_PORT
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: REDIS_PORT
        readinessProbe:
          httpGet:
            path: /health-check
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health-check
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 20