apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  postgresql.conf: |
    wal_level = replica
    max_wal_senders = 5
    wal_keep_size = 64
    listen_addresses = '*'
    port = 5432
  pg_hba.conf: |
    local   all             all                                     peer
    host    all             all             0.0.0.0/0               md5