apiVersion: v1
kind: Service
metadata:
  name: junjun-service
spec:
  type: ClusterIP  # ClusterIP 설정
  selector:
    app: junjun-app
  ports:
    - protocol: TCP
      port: 80          # 서비스가 노출하는 포트
      targetPort: 80    # Pod에서 사용하는 포트
