# Generated by Django 5.1 on 2024-09-20 05:02

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "상품 분류",
                "verbose_name_plural": "상품 분류",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("total_amount", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUSETED", "주문 요청"),
                            ("FAILED_PAYMENT", "결제 실패"),
                            ("PAID", "결제 완료"),
                            ("PREPARED_PRODUCT", "상품 준비 중"),
                            ("SHIPPED", "배송 중"),
                            ("DELIVERED", "배송 완료"),
                            ("CANCELLED", "주문 취소"),
                        ],
                        default="REQUSETED",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "주문",
                "verbose_name_plural": "주문",
                "ordering": ["-pk"],
            },
        ),
        migrations.CreateModel(
            name="OrderPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        default=dict, editable=False, verbose_name="포트원 결제내역"
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="쇼핑몰 결제식별자",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        editable=False, max_length=200, verbose_name="결제명"
                    ),
                ),
                (
                    "desired_amount",
                    models.PositiveIntegerField(
                        editable=False, verbose_name="결제요청금액"
                    ),
                ),
                (
                    "buyer_name",
                    models.CharField(
                        editable=False, max_length=100, verbose_name="구매자명"
                    ),
                ),
                (
                    "buyer_email",
                    models.EmailField(
                        editable=False, max_length=254, verbose_name="구매자 이메일"
                    ),
                ),
                (
                    "pay_method",
                    models.CharField(
                        choices=[
                            ("card", "카드 결제"),
                            ("virutal_account", "가상계좌 결제"),
                        ],
                        default="card",
                        max_length=20,
                    ),
                ),
                (
                    "pay_status",
                    models.CharField(
                        choices=[
                            ("READY", "미결제"),
                            ("PAID", "결제완료"),
                            ("CANCELLED", "결제취소"),
                            ("FAILED", "결제실패"),
                            ("VIRTUAL_ACCOUNT_ISSUED", "가상계좌"),
                        ],
                        default="READY",
                        max_length=22,
                    ),
                ),
                (
                    "is_paid_ok",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="결제성공여부"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="mall.order",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="설명"),
                ),
                ("price", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("a", "판매 중"),
                            ("i", "판매 중지"),
                            ("s", "품절"),
                            ("o", "단종"),
                        ],
                        default="a",
                        max_length=1,
                    ),
                ),
                (
                    "specifications",
                    models.JSONField(default=dict, verbose_name="제품 사양"),
                ),
                (
                    "presentation_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="mall/product/presentation/%Y/%m/%d",
                        verbose_name="Presentation 이미지",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="mall.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "상품",
                "verbose_name_plural": "상품",
                "ordering": ["-pk"],
            },
        ),
        migrations.CreateModel(
            name="OrderedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="주문 시점의 상품명을 저장합니다.", max_length=100
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        help_text="주문 시점의 상품가격을 저장합니다."
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="수량")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordered_products",
                        to="mall.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mall.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="product_set",
            field=models.ManyToManyField(
                through="mall.OrderedProduct", to="mall.product"
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="댓글 내용")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="mall.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="mall/product/images/%Y/%m/%d")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="mall.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "상품 이미지",
                "verbose_name_plural": "상품 이미지",
            },
        ),
        migrations.CreateModel(
            name="ProductOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("additional_price", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="mall.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="orderedproduct",
            name="option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mall.productoption",
            ),
        ),
        migrations.CreateModel(
            name="CartProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mall.product",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mall.productoption",
                    ),
                ),
            ],
            options={
                "verbose_name": "장바구니 상품",
                "verbose_name_plural": "장바구니 상품",
            },
        ),
        migrations.AddConstraint(
            model_name="orderedproduct",
            constraint=models.UniqueConstraint(
                fields=("order", "product", "option"),
                name="unique_order_product_option",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartproduct",
            constraint=models.UniqueConstraint(
                fields=("user", "product", "option"), name="unique_user_product_option"
            ),
        ),
    ]
