# Generated by Django 5.1 on 2024-10-04 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0002_alter_product_options_orderedproduct_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                db_constraint=False,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="mall.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sub_detail_category",
            field=models.ForeignKey(
                db_constraint=False,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="mall.subdetailcategory",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                db_constraint=False,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="mall.subcategory",
            ),
        ),
    ]
