# Generated by Django 5.1 on 2024-10-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0003_alter_product_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="shipping_info",
            field=models.TextField(blank=True, null=True, verbose_name="배송 정보"),
        ),
    ]
